export type SheetSchema = { sheetName: string; columns: string[]; description: string };

const BASE_IMPORT_COLUMNS = ['Mã dòng dữ liệu', 'Mã lần import'];
const AUDIT_COLUMNS = ['Tên file nguồn', 'Dấu vết dòng', 'Trạng thái dữ liệu', 'Ngày import', 'Người import'];

export const GOOGLE_SHEETS_SCHEMA: SheetSchema[] = [
  {
    sheetName: 'DL_DOANH_THU_APP',
    description: 'Dữ liệu gốc từ file tổng hợp doanh thu app.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kênh bán', 'Tài khoản app', 'Doanh thu gộp', 'Tổng khấu trừ/phí', 'Doanh thu ròng', 'Số đơn', 'Giá vốn', 'Giá trị đơn trung bình', 'Tỷ lệ phí', 'Tên file nguồn', 'Dấu vết file', 'Dấu vết dòng', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  {
    sheetName: 'DL_DOANH_THU_CUA_HANG',
    description: 'Dữ liệu gốc từ file báo cáo doanh thu tại cửa hàng.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Ca bán', 'Tổng phần', 'Số hộp', 'Số dĩa', 'Tiền mặt', 'MoMo/chuyển khoản', 'Chi tiền mặt', 'Tổng doanh thu theo file', 'Doanh thu bán hàng thực', 'Tiền mặt còn lại sau chi', 'Tên file nguồn', 'Dấu vết file', 'Dấu vết dòng', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  {
    sheetName: 'DL_SO_QUY',
    description: 'Dữ liệu gốc từ file sổ quỹ.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Mã phiếu', 'Loại giao dịch', 'Nhóm thu/chi', 'Diễn giải', 'Số tiền', 'Giá trị', 'Phương thức', 'Số dư sau giao dịch', 'Người tạo', 'Tên file nguồn', 'Dấu vết dòng', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  {
    sheetName: 'DL_TON_KHO',
    description: 'Dữ liệu gốc từ file tồn kho.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Ngày kiểm kê', 'Chi nhánh', 'Mã hàng', 'Tên hàng', 'Nhóm hàng', 'Đơn vị tính', 'Tồn kho', 'Giá trị tồn', 'Trạng thái tồn âm', 'Định mức tồn tối thiểu', 'Định mức tồn tối đa', 'Tên file nguồn', 'Dấu vết dòng', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  {
    sheetName: 'DL_THAT_THOAT_NVL',
    description: 'Dữ liệu gốc từ file báo cáo thất thoát NVL tuần.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Chi nhánh', 'Năm', 'Tuần', 'Mã tuần', 'Tuần bắt đầu', 'Tuần kết thúc', 'Tên nguyên vật liệu', 'Loại nguyên vật liệu', 'Đơn vị tính', 'Tồn đầu kỳ', 'Nhập trong kỳ', 'Nhập từ bếp trung tâm', 'Nhập từ nhà cung cấp', 'Tiêu hao lý thuyết theo bán hàng', 'Tồn cuối kỳ lý thuyết', 'Tồn cuối kỳ thực tế', 'Tồn cuối từ sổ', 'Chênh lệch số lượng', 'Loại chênh lệch', 'Đơn giá', 'Giá trị chênh lệch', 'Tỷ lệ thất thoát', 'Định mức cho phép', 'Mức vượt định mức', 'Trạng thái', 'Ghi chú', 'Nguyên nhân AI đề xuất', 'Hành động đề xuất', 'Người phụ trách', 'Deadline xử lý', 'Tên file nguồn', 'Dấu vết dòng', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  {
    sheetName: 'DL_CONG_NO',
    description: 'Dữ liệu công nợ để mở rộng báo cáo cân đối.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Nhà cung cấp/Đối tượng', 'Nhóm công nợ', 'Phải trả', 'Đã trả', 'Còn phải trả', 'Đến hạn', 'Quá hạn', 'Cần CEO duyệt', 'Ghi chú', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  {
    sheetName: 'DL_THU_MUA',
    description: 'Dữ liệu thu mua để phân tích biến động giá.',
    columns: ['Mã dòng dữ liệu', 'Mã lần import', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Mặt hàng', 'NCC', 'Giá tuần trước', 'Giá tuần này', 'Chênh lệch giá', 'Số lượng mua', 'Tác động tiền', 'Đánh giá', 'Ghi chú', 'Trạng thái dữ liệu', 'Ngày import', 'Người import']
  },
  { sheetName: 'DM_CHI_NHANH', description: 'Danh mục chi nhánh.', columns: [...BASE_IMPORT_COLUMNS, 'Mã chi nhánh', 'Tên chi nhánh', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_KHO_CHI_NHANH', description: 'Danh mục kho chi nhánh.', columns: [...BASE_IMPORT_COLUMNS, 'Mã kho', 'Tên kho', 'Chi nhánh', 'Loại kho', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_MON_BAN', description: 'Danh mục món bán.', columns: [...BASE_IMPORT_COLUMNS, 'Mã món', 'Tên món', 'Nhóm món', 'Giá bán', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_NGUYEN_VAT_LIEU', description: 'Danh mục nguyên vật liệu.', columns: [...BASE_IMPORT_COLUMNS, 'Mã NVL', 'Mã hàng', 'Tên NVL', 'Tên hàng', 'Nhóm NVL', 'Đơn vị tính', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_CONG_THUC_CHE_BIEN', description: 'Định mức món bán theo NVL.', columns: [...BASE_IMPORT_COLUMNS, 'Mã món', 'Tên món', 'Mã NVL', 'Tên NVL', 'Định mức', 'Tỷ lệ hao hụt', 'Đơn vị tính', 'Chi nhánh', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_HAO_HUT_HOP_LE', description: 'Định mức hao hụt hợp lệ.', columns: [...BASE_IMPORT_COLUMNS, 'Mã NVL', 'Tên NVL', 'Nhóm NVL', 'Hao hụt hợp lệ', 'Tỷ lệ hao hụt', 'Ghi chú', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_DON_GIA_NVL', description: 'Đơn giá nguyên vật liệu.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày hiệu lực', 'Mã NVL', 'Tên NVL', 'Đơn giá', 'Giá vốn', 'NCC', 'Ghi chú', ...AUDIT_COLUMNS] },
  { sheetName: 'DM_NGUOI_DUNG', description: 'Tài khoản người dùng nội bộ, phân quyền và 2FA.', columns: ['user_id', 'username', 'display_name', 'email', 'google_workspace_email', 'role', 'branch_scope', 'status', 'password_hash', 'two_factor_enabled', 'two_factor_secret', 'backup_codes_hash', 'must_change_password', 'failed_login_count', 'last_login_at', 'last_password_change', 'created_at', 'updated_at', 'updated_by', 'note'] },
  { sheetName: 'DL_XNT_CUA_HANG', description: 'Xuất nhập tồn cửa hàng.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kho', 'Mã hàng', 'Tên hàng', 'Đơn vị tính', 'Tồn đầu', 'Nhập từ BTT', 'Nhập NCC', 'Nhập', 'Số lượng bán', 'Xuất', 'Hủy', 'Tồn lý thuyết', 'Tồn thực tế', 'Lệch', 'Giá trị lệch', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DL_XNT_BEP_TRUNG_TAM', description: 'Xuất nhập tồn Bếp Trung Tâm.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kho', 'Mã hàng', 'Tên hàng', 'Đơn vị tính', 'Tồn đầu', 'Giá trị tồn đầu', 'Nhập NCC', 'Giá trị nhập NCC', 'Xuất cửa hàng', 'Giá trị xuất cửa hàng', 'Tồn lý thuyết', 'Tồn thực tế', 'Giá trị tồn thực tế', 'Lệch', 'Giá trị lệch', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DL_XUAT_BTT_CHO_CUA_HANG', description: 'BTT xuất cho cửa hàng.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Cửa hàng', 'Mã phiếu', 'Kho xuất', 'Mã hàng', 'Tên hàng', 'Số lượng xuất', 'Số lượng', 'SL xuất', 'Giá trị xuất', 'Đơn vị tính', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DL_CUA_HANG_NHAN_TU_BTT', description: 'Cửa hàng nhận từ BTT.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Cửa hàng', 'Mã phiếu', 'Kho nhận', 'Mã hàng', 'Tên hàng', 'Số lượng nhận', 'Số lượng', 'SL nhận', 'Đơn vị tính', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DL_HUY_HANG_CUA_HANG', description: 'Hủy hàng cửa hàng.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày hủy', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kho', 'Mã hàng', 'Tên hàng', 'Số lượng', 'Giá trị hủy', 'Đơn giá', 'Lý do', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DL_HUY_HANG_BTT', description: 'Hủy hàng BTT.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày hủy', 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kho', 'Mã hàng', 'Tên hàng', 'Số lượng', 'Giá trị hủy', 'Đơn giá', 'Lý do', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'DL_CHE_BIEN_THUC_TE', description: 'Chế biến thực tế.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kho', 'Món', 'NVL', 'Thực tế dùng', 'Số lượng chế biến', 'Định mức', 'Ca', 'Người thực hiện', ...AUDIT_COLUMNS] },
  { sheetName: 'KQ_HAO_HUT_CHE_BIEN', description: 'Kết quả hao hụt chế biến.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Món', 'NVL', 'Thực tế dùng', 'Định mức', 'Hao hụt', 'Vượt định mức', 'Giá trị vượt', 'Ca', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'KQ_THAT_THOAT_TON_KHO', description: 'Kết quả thất thoát tồn kho.', columns: [...BASE_IMPORT_COLUMNS, 'Ngày', 'Năm', 'Tháng', 'Tuần', 'Mã tuần', 'Chi nhánh', 'Kho', 'NVL', 'Mã hàng', 'Tên hàng', 'Tồn lý thuyết', 'Tồn thực tế', 'Lệch', 'Giá trị thất thoát', 'Tỷ lệ', 'Trạng thái', ...AUDIT_COLUMNS] },
  { sheetName: 'TONG_QUAN_KE_TOAN', description: 'Tổng quan kế toán tuần.', columns: ['Khu vực', 'Chỉ số', 'Giá trị', 'Tuần trước', 'Chênh lệch', 'Trạng thái', 'Ghi chú'] },
  { sheetName: 'LICH_SU_CHOT_BAO_CAO', description: 'Lịch sử chốt báo cáo.', columns: ['Mã lần chốt', 'Mã tuần', 'Chi nhánh', 'Thời gian chốt', 'Người chốt', 'Trạng thái', 'Snapshot', 'Gửi CEO/Bot', 'Ghi chú'] },
  { sheetName: 'CEO_DASHBOARD', description: 'Sheet báo cáo tổng quan CEO.', columns: ['Khu vực', 'Chỉ số', 'Giá trị', 'Tuần trước', 'Chênh lệch', 'Trạng thái', 'Ghi chú'] },
  { sheetName: 'P&L_TUAN', description: 'Sheet báo cáo P&L tuần.', columns: ['Nhóm', 'Chỉ số', 'Tuần này', 'Tuần trước', 'Chênh lệch', 'Tỷ lệ', 'Đánh giá', 'Ghi chú'] },
  { sheetName: 'DONG_TIEN_TUAN', description: 'Sheet báo cáo dòng tiền tuần.', columns: ['Nhóm', 'Chỉ số', 'Số tiền', 'Tuần trước', 'Chênh lệch', 'Đã đối chiếu chưa', 'Ghi chú'] },
  { sheetName: 'CAN_DOI_RUT_GON', description: 'Sheet báo cáo cân đối rút gọn.', columns: ['Nhóm', 'Chỉ số', 'Số tiền', 'Tuần trước', 'Chênh lệch', 'Trạng thái', 'Ghi chú'] },
  { sheetName: 'DU_TOAN_TUAN_TOI', description: 'Sheet dự toán tuần tới.', columns: ['Nhóm dự toán', 'Chỉ số', 'Thực tế tuần vừa rồi', 'Dự toán tuần tới', 'Tăng/giảm', 'Cần CEO duyệt không', 'Lý do/Ghi chú'] },
  { sheetName: 'THAT_THOAT_CHI_TIET', description: 'Sheet báo cáo thất thoát chi tiết.', columns: ['Hạng', 'NVL', 'ĐVT', 'Chênh SL', 'Giá trị lệch', 'Tỷ lệ thất thoát', 'Định mức', 'Vượt định mức', 'Trạng thái', 'Hành động'] },
  { sheetName: 'BAN_LAM_VIEC_KE_TOAN', description: 'Checklist công việc kế toán.', columns: ['Việc cần làm', 'Trạng thái', 'Người phụ trách', 'Deadline', 'File nguồn', 'Lỗi/Cảnh báo', 'Hành động'] },
  { sheetName: 'IMPORT_LICH_SU', description: 'Lịch sử import batch/file.', columns: ['Mã lần import', 'Ngày import', 'Người import', 'Chi nhánh', 'Tuần', 'Số file', 'Tổng dòng mới', 'Tổng dòng trùng', 'Tổng dòng lệch', 'Tổng dòng lỗi', 'Trạng thái', 'Ghi chú'] },
  { sheetName: 'IMPORT_DONG_LOI', description: 'Dòng lỗi khi preview/import.', columns: ['Mã lỗi', 'Mã lần import', 'Tên file', 'Dòng nguồn', 'Sheet nguồn', 'Trường lỗi', 'Giá trị lỗi', 'Mô tả lỗi', 'Mức độ', 'Cách xử lý', 'Trạng thái'] },
  { sheetName: 'IMPORT_DU_LIEU_TRUNG', description: 'Dữ liệu trùng khi preview/import.', columns: ['Mã trùng', 'Mã lần import', 'Tên file', 'Dòng nguồn', 'Khóa dữ liệu', 'Dữ liệu hiện có', 'Dữ liệu mới', 'Hành động'] },
  { sheetName: 'IMPORT_DU_LIEU_LECH', description: 'Dữ liệu lệch khi preview/import.', columns: ['Mã lệch', 'Mã lần import', 'Tên file', 'Khóa dữ liệu', 'Chỉ số lệch', 'Giá trị cũ', 'Giá trị mới', 'Chênh lệch', 'Người xử lý', 'Trạng thái'] },
  { sheetName: 'AUDIT_LOG', description: 'Audit log hành động hệ thống.', columns: ['ID', 'Thời gian', 'Người dùng', 'Vai trò', 'Hành động', 'Đối tượng', 'Trước', 'Sau', 'Ghi chú', 'IP/Thiết bị'] },
  { sheetName: 'CAI_DAT_BOT', description: 'Cài đặt bot báo cáo, không lưu secret thật.', columns: ['Cấu hình', 'Giá trị', 'Ghi chú', 'Trạng thái'] },
  { sheetName: 'CAI_DAT_NGUONG', description: 'Cài đặt ngưỡng cảnh báo.', columns: ['Chỉ số', 'Tốt', 'Cảnh báo', 'Nguy hiểm', 'Đơn vị', 'Áp dụng cho', 'Ghi chú'] },
  { sheetName: '01_CONFIG_MASTER', description: 'Option C - danh mục nền, ngưỡng cảnh báo, cửa hàng/kho, nhóm chi phí và user hash nội bộ.', columns: ['config_type', 'ma', 'ten', 'nhom', 'mo_ta', 'gia_tri', 'don_vi', 'ap_dung_tu_ngay', 'trang_thai', 'nguoi_duyet', 'ghi_chu'] },
  { sheetName: '02_DM_CONG_THUC_DINH_MUC', description: 'Option C - công thức món bán, định mức NVL, hao hụt hợp lệ.', columns: ['ma_cong_thuc', 'ma_mon', 'ten_mon', 'ma_nvl', 'ten_nvl', 'dvt_nvl', 'dinh_muc_1_don_vi', 'hao_hut_hop_le_pct', 'kho_ap_dung', 'kenh_ap_dung', 'hieu_luc_tu_ngay', 'trang_thai', 'nguoi_duyet', 'ghi_chu', 'import_batch_id', 'nguon_file', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '03_IMPORT_LOG_SYSTEM_LOG', description: 'Option C - lịch sử upload, lỗi, log thao tác và AI log.', columns: ['log_id', 'log_type', 'thoi_gian', 'user', 'role', 'module', 'file_name', 'file_type', 'ky_bao_cao', 'so_dong_doc', 'so_dong_hop_le', 'so_dong_loi', 'ket_qua', 'noi_dung_loi', 'hanh_dong_tiep_theo', 'ghi_chu'] },
  { sheetName: '04_DATA_DOANH_THU', description: 'Option C - doanh thu offline/app/chuyển khoản.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'cua_hang', 'ca_ban', 'kenh_ban', 'ma_mon', 'ten_mon', 'so_luong_ban', 'doanh_thu_gross', 'giam_gia', 'phi_app', 'hoan_huy', 'doanh_thu_net', 'tien_thuc_nhan', 'chung_tu', 'nguon_file', 'trang_thai', 'import_batch_id', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '05_DATA_SO_QUY', description: 'Option C - thu chi, sổ quỹ, dòng tiền.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'cua_hang', 'loai_giao_dich', 'nhom_thu_chi', 'noi_dung', 'so_tien_thu', 'so_tien_chi', 'phuong_thuc', 'doi_tuong', 'chung_tu', 'nguoi_duyet', 'trang_thai', 'nguon_file', 'ghi_chu', 'import_batch_id', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '06_DATA_CONG_NO', description: 'Option C - công nợ NCC/app/khác.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'loai_cong_no', 'doi_tuong', 'ma_doi_tuong', 'no_dau_ky', 'phat_sinh_tang', 'phat_sinh_giam', 'no_cuoi_ky', 'han_thanh_toan', 'trang_thai_doi_chieu', 'trang_thai_thanh_toan', 'muc_canh_bao', 'ghi_chu', 'import_batch_id', 'nguon_file', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '07_DATA_NHAN_SU_LUONG', description: 'Option C - chấm công, tạm ứng, thưởng/phạt, bảng lương.', columns: ['row_id', 'ky_luong', 'nhan_vien', 'vai_tro', 'cua_hang', 'so_cong', 'gio_lam', 'di_tre', 'nghi', 'ca_gay', 'tam_ung', 'thuong', 'phat', 'phu_cap', 'luong_tam_tinh', 'khau_tru', 'thuc_nhan', 'trang_thai_duyet', 'ghi_chu', 'import_batch_id', 'nguon_file', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '08_DATA_KHO_CUA_HANG', description: 'Option C - dữ liệu kho cửa hàng sau upload.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'cua_hang', 'ma_kho', 'ma_hang', 'ten_hang', 'dvt', 'ton_dau', 'nhap_tu_btt', 'nhap_ncc', 'so_luong_ban', 'huy_hop_le', 'kiem_ke_thuc_te', 'dieu_chinh_tang', 'dieu_chinh_giam', 'don_gia_von', 'nguon_file', 'trang_thai', 'ghi_chu', 'import_batch_id', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '09_DATA_KHO_BTT', description: 'Option C - dữ liệu kho bếp trung tâm.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'ma_kho_btt', 'ma_hang', 'ten_hang', 'dvt', 'ton_dau', 'nhap_ncc', 'san_xuat_so_che_dau_vao', 'san_xuat_so_che_dau_ra', 'huy_hop_le_btt', 'kiem_ke_thuc_te_btt', 'dieu_chinh_tang', 'dieu_chinh_giam', 'don_gia_von', 'nguon_file', 'trang_thai', 'ghi_chu', 'import_batch_id', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '10_DATA_XUAT_BTT_CUA_HANG', description: 'Option C - xuất BTT cho cửa hàng, mapping từ file Xuất Hủy.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'ma_kho_xuat', 'kho_xuat', 'cua_hang_nhan', 'ma_kho_nhan', 'ma_hang', 'ten_hang', 'dvt', 'so_luong_xuat', 'so_luong_cua_hang_xac_nhan', 'chenh_lech_xuat_nhan', 'gia_tri_xuat', 'trang_thai_nhan', 'nguoi_xac_nhan', 'nguon_file', 'ghi_chu', 'import_batch_id', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '11_DATA_HANG_HUY_KIEM_KE', description: 'Option C - hàng hủy thật và kiểm kê thực tế chi tiết.', columns: ['row_id', 'ky_bao_cao', 'ngay', 'loai_du_lieu', 'loai_kho', 'cua_hang_hoac_btt', 'ma_kho', 'ma_hang', 'ten_hang', 'dvt', 'so_luong', 'don_gia_von', 'gia_tri', 'ly_do', 'nguoi_ghi_nhan', 'nguoi_duyet', 'chung_tu_anh', 'trang_thai', 'ghi_chu', 'import_batch_id', 'nguon_file', 'imported_at', 'imported_by', 'trang_thai_dong'] },
  { sheetName: '12_CALC_TON_KHO', description: 'Option C - tính tồn lý thuyết, tồn cuối, tồn đầu kỳ sau.', columns: ['ky_bao_cao', 'loai_kho', 'ma_kho', 'ten_kho', 'ma_hang', 'ten_hang', 'dvt', 'ton_dau', 'tong_nhap', 'tieu_hao_ly_thuyet', 'xuat_btt_cho_cua_hang', 'huy_hop_le', 'dieu_chinh_tang', 'dieu_chinh_giam', 'ton_ly_thuyet', 'kiem_ke_thuc_te', 'chenh_lech_ton', 'thieu_kho', 'du_kho', 'gia_tri_lech', 'ton_cuoi_chot', 'ton_dau_ky_sau', 'muc_canh_bao', 'hanh_dong_de_xuat'] },
  { sheetName: '13_CALC_HAO_HUT_THAT_THOAT', description: 'Option C - tính vượt định mức và thất thoát tồn kho.', columns: ['ky_bao_cao', 'loai_kho', 'ma_kho', 'ma_mon', 'ten_mon', 'ma_nvl', 'ten_nvl', 'dvt', 'so_luong_ban_hoac_san_luong', 'dinh_muc_chuan', 'hao_hut_hop_le_pct', 'nvl_duoc_phep_dung', 'nvl_thuc_te_dung', 'vuot_dinh_muc_sl', 'ty_le_vuot_dinh_muc', 'gia_tri_vuot_dinh_muc', 'thieu_kho', 'thieu_kho_pct', 'gia_tri_that_thoat_ton_kho', 'muc_canh_bao', 'hanh_dong_de_xuat'] },
  { sheetName: '14_CALC_TAI_CHINH_DU_TOAN', description: 'Option C - tính dòng tiền, cân đối, dự toán.', columns: ['ky_bao_cao', 'ngay_bat_dau', 'ngay_ket_thuc', 'doanh_thu_thuc_te', 'tong_thu', 'tong_chi', 'dong_tien_tam', 'cong_no_den_han', 'so_du_dau_ky', 'so_du_cuoi_ky', 'doanh_thu_tb_4_tuan', 'doanh_thu_du_toan_tuan_toi', 'chi_bien_doi_du_toan', 'chi_co_dinh_du_toan', 'cong_no_can_tra_tuan_toi', 'so_du_du_kien', 'muc_canh_bao', 'hanh_dong_de_xuat'] },
  { sheetName: '15_DASHBOARD_REPORT', description: 'Option C - output đã tổng hợp cho app web đọc đầu tiên và dashboard từng tab con.', columns: ['report_id', 'ky_bao_cao', 'ngay_cap_nhat', 'module', 'sub_module', 'metric_key', 'metric_name', 'gia_tri', 'don_vi', 'chu_ky', 'so_sanh_ky_truoc', 'muc_canh_bao', 'display_type', 'display_order', 'nguon_sheet', 'nguon_du_lieu', 'hanh_dong_de_xuat', 'nguoi_phu_trach', 'trang_thai', 'link_chi_tiet', 'updated_at'] }
];
