export const AUDIT_EVENTS = {
  IMPORT_PREVIEW: 'IMPORT_PREVIEW',
  IMPORT_CONFIRM: 'IMPORT_CONFIRM',
  IMPORT_ROLLBACK: 'IMPORT_ROLLBACK',
  CONFLICT_RESOLVE: 'CONFLICT_RESOLVE',
  CONFIG_CHANGE: 'CONFIG_CHANGE'
} as const;

export type AuditEventType = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];
